### ISSUE TITLE
Error on hanging up call

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-call#467]
### Steps to reproduce

This console message on hangup:

```
Uncaught TypeError: Cannot destructure property 'onCallFeedsChanged' of 'this.callHandlers.get(...)' as it is undefined.
    at FZ.disposeCall (groupCall.ts:988:13)
    at FZ.removeCall (groupCall.ts:937:14)
    at FZ.dispose (groupCall.ts:356:18)
    at FZ.leave (groupCall.ts:379:14)
    at useGroupCall.ts:292:45
    at GroupCallView.jsx:78:11
    at j (module.js:242:55)
    at HTMLDocument.ae (module.js:395:78)
    at HTMLDocument.i (helpers.js:74:23)
```

UI changed to 'waiting for other participants'

### Will you send logs?

Yes

**Comment by dbkr** [comment]
Probably fair to assume this is fixed if we haven't seen it since (which I haven't).
