### ISSUE TITLE
Soft crash when another user hung up in embedded mode

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-call#713]
### Steps to reproduce

Joined from three clients in embedded mode, left on one.

### Outcome

ypeError: Cannot read properties of undefined (reading 'name')
    at ZRe (useRoomMemberName.ts:29:18)
    at lZ (VideoTileContainer.tsx:69:30)
    at JH (react-dom.production.min.js:167:137)
    at xF (react-dom.production.min.js:197:258)
    at Pte (react-dom.production.min.js:292:88)
    at Ote (react-dom.production.min.js:280:389)
    at Uge (react-dom.production.min.js:280:320)
    at TR (react-dom.production.min.js:280:180)
    at DF (react-dom.production.min.js:271:88)
    at Ite (react-dom.production.min.js:268:429)
    at G (scheduler.production.min.js:13:203)
    at MessagePort.oe (scheduler.production.min.js:14:128)

Soft crash screen disappeared before I could send logs.

### Will you send logs?

No

**Comment by robintown** [comment]
Cause is probably:

![error](https://user-images.githubusercontent.com/48614497/199821401-7a966b16-e894-4b63-8342-6ebadd0b478f.png)
